version: "3.3"

services:
        react:
                container_name: rrweb_dev_client 
                image: recipe_rest_client_dev 
                build:
                        context: ./frontend
                        dockerfile: Dockerfile.dev
                volumes:
                        - './frontend:/app'
                ports:
                        - "3000:3000"
                environment:
                        - CHOKIDAR_USEPOLLING=true
                stdin_open: true
                tty: true
        golang:
                container_name: rrweb_dev_server
                image: recipe_rest_server_dev
                build: 
                        context: ./backend
                        dockerfile: Dockerfile.dev
                volumes:
                        - './backend/data:/app/data'
                ports:
                        - "8080:8080"
