# Bulder
FROM golang:alpine as builder
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN go build -o main /app/cmd/rrweb/main.go

# Runner
FROM alpine
ENV USER=appuser
RUN adduser \
    --disabled-password \
    --home "/app" \
    --no-create-home \
    "$USER"
# RUN mkdir -p /app/data

# COPY ./data /app/data
COPY --from=builder /app/main /app/
RUN chown -R "$USER" /app
USER appuser
WORKDIR /app
CMD ["./main"]
